### ISSUE TITLE
Consider EnsureSuccess / EnsureFailure? Or at least ThrowFailure in case where failure is exception.

### ISSUE THREAD

**Issue by JohannesMoersch** [JohannesMoersch/Functional#22]

**Comment by JohannesMoersch** [comment]
Also EnsureValue?

**Comment by RyanMarcotte** [comment]
I have ended up using all of the following because these proposed extension methods do not exist yet:
- `option.Match(value => value, () => throw new Exception(...))`
- `result.Match(success => success, failure => throw new Exception(...))`
- `result.Match(success => success, exception => throw new Exception(exception))` (preserves original exception stack trace)

Have not found need for throwing exception on success personally, but it would be useful to have.

IMO, `ThrowIfNone`, `ThrowIfFailure`, `ThrowIfSuccess` would be more descriptive names than `EnsureValue`, `EnsureSuccess`, `EnsureFailure`.  Curious what your thoughts are on that.
