### ISSUE TITLE
Consider adding Result.Merge factory methods to produce Result<(T1, ..., Tn), TFailure[]>

### ISSUE THREAD

**Issue by RyanMarcotte** [JohannesMoersch/Functional#84]
Suppose the following smart constructors are defined:
```
Result<A, TFailure> CreateA(...)
Result<B, TFailure> CreateB(...)
Result<C, TFailure> CreateC(...)
```

For each of the above, a successful result containing an object `A`, `B`, or `C` is returned when inputs are valid; otherwise, a faulted result is returned.

A chain of `Bind` methods like the following will only return the first validation error.
```
CreateA(...)
    .Bind(a => CreateB(...).Select(b => (a, b)))
    .Bind(t => CreateC(...).Select(c => new Thing(t.a, t.b, c)));
```

I want to return _all_ validation errors.

```
// implemented in my own codebase for now...  this could likely be cleaned up with internal library utility methods
public static class Result
{
	public static Result<(TSuccess1, TSuccess2), TFailure[]> Merge<TSuccess1, TSuccess2, TFailure>(Result<TSuccess1, TFailure> r1, Result<TSuccess2, TFailure> r2)
	{
		return (from s1 in r1.Success() from s2 in r2.Success() select (s1, s2))
			.ToResult(() => CombineFailures(r1.Failure(), r2.Failure()));
	}

	public static Result<(TSuccess1, TSuccess2, TSuccess3), TFailure[]> Merge<TSuccess1, TSuccess2, TSuccess3, TFailure>(Result<TSuccess1, TFailure> r1, Result<TSuccess2, TFailure> r2, Result<TSuccess3, TFailure> r3)
	{
		return (from s1 in r1.Success() from s2 in r2.Success() from s3 in r3.Success() select (s1, s2, s3))
			.ToResult(() => CombineFailures(r1.Failure(), r2.Failure(), r3.Failure()));
	}

	public static Result<(TSuccess1, TSuccess2, TSuccess3, TSuccess4), TFailure[]> Merge<TSuccess1, TSuccess2, TSuccess3, TSuccess4, TFailure>(Result<TSuccess1, TFailure> r1, Result<TSuccess2, TFailure> r2, Result<TSuccess3, TFailure> r3, Result<TSuccess4, TFailure> r4)
	{
		return (from s1 in r1.Success() from s2 in r2.Success() from s3 in r3.Success() from s4 in r4.Success() select (s1, s2, s3, s4))
			.ToResult(() => CombineFailures(r1.Failure(), r2.Failure(), r3.Failure(), r4.Failure()));
	}

	public static Result<(TSuccess1, TSuccess2, TSuccess3, TSuccess4, TSuccess5), TFailure[]> Merge<TSuccess1, TSuccess2, TSuccess3, TSuccess4, TSuccess5, TFailure>(Result<TSuccess1, TFailure> r1, Result<TSuccess2, TFailure> r2, Result<TSuccess3, TFailure> r3, Result<TSuccess4, TFailure> r4, Result<TSuccess5, TFailure> r5)
	{
		return (from s1 in r1.Success() from s2 in r2.Success() from s3 in r3.Success() from s4 in r4.Success() from s5 in r5.Success() select (s1, s2, s3, s4, s5))
			.ToResult(() => CombineFailures(r1.Failure(), r2.Failure(), r3.Failure(), r4.Failure(), r5.Failure()));
	}

	private static TFailure[] CombineFailures<TFailure>(params Option<TFailure>[] failureCollection)
		=> failureCollection.SelectMany(x => x.ToEnumerable()).ToArray();

	private static IEnumerable<TFailure> ToEnumerable<TFailure>(this Option<TFailure> source)
	{
		if (source.HasValue())
			yield return source.Match(x => x, () => default);
	}
}
```

Sample usage:
```
return Result.Merge(result1, result2, result3, result4, result5)
	.Select(t => new Thing(t.Item1, t.Item2, t.Item3, t.Item4, t.Item5));
```

**Comment by RyanMarcotte** [comment]
@JohannesMoersch , if you sign off on the idea, I can go ahead and implement it

**Comment by RyanMarcotte** [comment]
The book [Functional Programming in C#](https://www.manning.com/books/functional-programming-in-c-sharp) lists code for aggregating multiple `Result` into a single `Result`, but it is not quite the same as the use case I previously described.  The author only accounts for identical subject types `T` (i.e. executing multiple validation rules on the same subject) rather than distinct subject types.

``` csharp
// the following is loosely copied from the book
public delegate Result<T, IEnumerable<Error>> Validator(T subject);

public static Validator<T> HarvestErrors(this IEnumerable<Validator<T>> validators)
=> t =>
{
    var errors = validators
        .Map(validate => validate(t)) // run all validators
        .Bind(v => v.Match(  // collect validation errors
            _ => None,
            errs => Some(errs)))  // Option<T> implements IEnumerable<T>
        .ToList();

    return errors.Count == 0
        ? Success(t)
        : Failure(errors.Flatten());
}
```

**Comment by RyanMarcotte** [comment]
More thoughts on naming...  `Result.Aggregate(...)` is the same concept as the existing `Result<TSuccess[], TFailure[]> TakeAll<TSuccess, TFailure>(this IEnumerable<Result<TSuccess, TFailure>> source)` except the individual `Result` objects in `source` can have varying `TSuccess` types.  Would we want the new function to be named something similar?

**Comment by RyanMarcotte** [comment]
Can I get some input on the latest naming suggestions @NathanMagnus , @deimors , @JohannesMoersch , @mich4xD ?

**Comment by NathanMagnus** [comment]
I'm not sure I like `TakeAll`. Due to `Take` existing on `IEnumerable`, I think that implies that the input would be an `IEnumerable`. Similarly, `Aggregate` also exists on `IEnumerable`. While `Merge` is used for `DataTable`s I think it is less likely to cause confusion vs methods on `IEnumerable`. So, my vote is `Merge`.

All that being said, if there is a commonly accepted name for this operation in other functional languages or literature, I think that would be the best way to go.

**Comment by RyanMarcotte** [comment]
Thank you for the input!  Correct, `TakeAll` is not the correct method name here due it existing already as an extension method off `IEnumerable<Result<TSuccess, TFailure>>`.  I am merely wondering if we would want to use a similar naming style used elsewhere in the library...  I too agree that a commonly-accepted name from functional languages would be better.

From https://en.wikipedia.org/wiki/Fold_(higher-order_function)

>In functional programming, **fold** (also termed **reduce**, **accumulate**, **aggregate**, **compress**, or **inject**) refers to a family of higher-order functions that analyze a recursive data structure and through use of a given combining operation, recombine the results of recursively processing its constituent parts, building up a return value. Typically, a fold is presented with a combining function, a top node of a data structure, and possibly some default values to be used under certain conditions. The fold then proceeds to combine elements of the data structure's hierarchy, using the function in a systematic way.

In our case, the recursive data structure is the collection of `Result<TSuccess, TFailure>` with varying `TSuccess` types.

IMO, I don't think there would be any confusion with LINQ.  The syntax being proposed is the static factory method `Result.Aggregate(...)` vs LINQ's extension method syntax `someCollection.Aggregate(...)`.  I think that some familiarity with LINQ's `Aggregate` function will make the usage of the new function more immediately apparent (iterate over a collection and produce a single value) without having to dive into the repository documentation.  I will be writing up documentation regardless.

**Comment by andrewk-iq** [comment]
Late to the party 👋, but my 2 cents? What's missing in order to properly use the language of Aggregate, Accumulate, Fold, etc., is the _combining operator_ mentioned in that wiki snippet, ie: a function that operates on the inputs in order to produce the output. 

This extension method is really more of, I dunno, a structural concatenation?

For the example you've given above:

```
return Result.Merge(result1, result2, result3, result4, result5)
	.Select(t => new Thing(t.Item1, t.Item2, t.Item3, t.Item4, t.Item5));
```

In other "functional-style" libraries, this would usually be written as something like:

```
return Result.Merge(result1, result2, result3, result4, result5, (r1, r2, r3, r4, r5) => new Thing(r1, r2, r3, r4, r5));
```

See: `Zip` operator in System.Reactive https://docs.microsoft.com/en-us/previous-versions/dotnet/reactive-extensions/hh211957(v=vs.103), `Zip` operator in Linq https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.zip?view=netframework-4.8

Hmm, y'know, I'm seeing a pattern: `Zip` operators take in heterogeneous lifted types (such as `IObservable<T1>`, `IObservable<T2>`, etc.) whereas `Merge` operators take in homogeneous lifted types (eg: multiple `IEnumerable<T>`, that sort of thing; consider https://docs.microsoft.com/en-us/previous-versions/dotnet/reactive-extensions/hh229590(v=vs.103)).

Maybe `Zip` would be a reasonable name for the extension method?

I do think the more standard way to represent this would be to take in combining operators, for result likely over both the successes and failures.

eg:

```
Result<TSuccessOut, TFailureOut> Zip(
    Result<TSuccess1, TFailure1> r1, 
    Result<TSuccess2, TFailure2> r2, 
    Func<TSuccess1, TSuccess2, TSuccessOut> successOperator, 
    Func<TFailure1, TFailure2, TFailureOut> failureOperator
)
```

This is the more general form, but maybe you're seeing the "homogenous failure type" as the more common / useful case to solve for, with concatenation as the normal operator on the failure instances:

```
Result<TSuccessOut, IEnumerable<TFailure>> Zip(
    Result<TSuccess1, TFailure> r1, 
    Result<TSuccess2, TFailure> r2, 
    Func<TSuccess1, TSuccess2, TSuccessOut> successOperator
)
```

This is essentially the signature of the method I used above; if you need to construct a tuple out of the successes, you can, however if the goal is to create some output type that's not a tuple then this is the more direct method.

**Comment by andrewk-iq** [comment]
If you're intent on having an operator do exactly what your "Merge" operator is doing, then it might be worthwhile to include the specificity in the name, eg: `ZipToTuple` or `TupleZip`. But I think it's important to distinguish that this is a special case of a more general operator.

**Comment by RyanMarcotte** [comment]
Thank you for the input @andrewk-iq!  I had forgotten about LINQ's `Zip` extension method as I don't use it too often.  I like the `Zip` functions you've proposed: [a function which maps a tuple of sequences into a sequence of tuples](https://en.wikipedia.org/wiki/Convolution_(computer_science)).

`(r1s, r1f), (r2s, r2f) => (r1s, r2s), (r1f, r2f)`, and we either discard `(r1s, r2s)` if 

I wonder if we _need_ the `Func<TSuccess1, TSuccess2, TSuccessOut>`, `Func<TFailure1, TFailure2, TFailureOut>` parameters though?  Developers can use the raw tuple _or_ use `Map` + `MapOnFailure` to map to the desired types.  I may be able to write a zero-allocation version of `Zip` using value tuples.

```
Result<(TSuccess1, TSuccess2), (TFailure1, TFailure2)> Zip(
    Result<TSuccess1, TFailure1> r1, 
    Result<TSuccess2, TFailure2> r2
)
    .Map(t => new Thing(t.Item1, t.Item2))
    .MapOnFailure(t => new[] { t.Item1, t.Item2 });
```

**Comment by RyanMarcotte** [comment]
Played around with it, and it will have to be a homogeneous `TFailure` type.  The signature proposed only works for "all success", "all failure" cases. I (we?) want "all success", "one or more failures" cases.

Result<(TSuccess1, TSuccess2), TFailure1[])> Zip(
    Result<TSuccess1, TFailure1> r1, 
    Result<TSuccess2, TFailure2> r2
)
    .Map(t => new Thing(t.Item1, t.Item2));

**Comment by andrewk-iq** [comment]
Cool! Yea, the tuple output is certainly an option, I just see that as being a more specialized case than passing in a delegate to map to the desired output type, but you're right that with a subsequent `Map` operation you can easily take that tuple to whatever type you'd like.

As for your point about the homogeneous failure type, yea, I'd overlooked that bit of the semantics, "all successes" / "one or more failures" does make sense.

You've had me wondering a bit about the original intent for this extension method, ie: the ability to chain together validators returning results by executing all of them and gathering the successes / failures. The current approach seems to limit the number of validators to the number of variants of this method that you've defined for different numbers of result inputs, no? It makes me wonder about creating an extension method that can just be chained as many times as you want, rather than being limited to a maximum number of parameters?

eg:
```
Result<TNewSuccess, TFailure[]> Chain(
    this Result<TSourceSuccess, TFailure[]> source, 
    Result <TOtherSuccess, TFailure> other,
    Func<TSourceSuccess, TOtherSuccess, TNewSuccess> combinator
)
```

You could use this to construct a tuple output if that's what you're looking for, but the tuple doesn't need to be apparent in the type signature.

eg:
```
ValidatorA(thing).MapFailure(f => new[] { f })
    .Chain(ValidatorB(thing), (s1, s2) => (s1, s2))
    .Chain(ValidatorC(thing), (t, s3) => (t.s1, t.s2, s3))
```

If you're just looking to pass along a single success type (such as the thing being validated, or `Unit`) this is easy enough as well, but it does open the possibility for composition without limiting the number of things being composed. You do have to specify the tuple composition (if you're looking to construct a tuple), but if that's a common enough case I suppose you could specify extension methods for handling up to n-tuples while leaving the >n general case open to manual construction (if need be).

(Also, not advocating for the name `Chain`, it was just the first thing I could thing of.)

**Comment by RyanMarcotte** [comment]
I had been mulling some variation of unlimited method chaining as well but was coming up blank. I'll play around with it again today now that I have your signature as a starting point.

I don't think `Append` is the right word either, but that's the only word I can think of currently.

Could still be `Zip`.

**Comment by RyanMarcotte** [comment]
I'll experiment with some kind of fluent builder implementation too that does not require mapping at every individual step

**Comment by RyanMarcotte** [comment]
As for original intent of the `Zip` method, it's not strictly for validation but for building a smart constructor using the smart constructors of other objects.

From a personal project:
``` csharp
public static Result<Address, AddressValidationError[]> Create(string street, string city, string stateOrProvince, string iso3166CountryCode, string postalCode)
{
	if (street == null) throw new ArgumentNullException(nameof(street));
	if (city == null) throw new ArgumentNullException(nameof(city));
	if (stateOrProvince == null) throw new ArgumentNullException(nameof(stateOrProvince));
	if (postalCode == null) throw new ArgumentNullException(nameof(postalCode));
	if (iso3166CountryCode == null) throw new ArgumentNullException(nameof(iso3166CountryCode));

	var streetResult = Result.Create(!string.IsNullOrWhiteSpace(street), () => street, () => AddressValidationError.ForInvalidStreet);

	var cityResult = Result.Create(!string.IsNullOrWhiteSpace(city), () => city, () => AddressValidationError.ForInvalidCity);

	var countryCodeResult = ISO3166CountryCode.Create(iso3166CountryCode).MapOnFailure(AddressValidationError.ForInvalidCountry);

	var stateOrProvinceResult = Result.Create(!string.IsNullOrWhiteSpace(stateOrProvince), () => Unit.Value, () => AddressValidationError.ForInvalidStateOrProvince(StateOrProvinceValidationError.IsEmpty))
		.Bind(_ => countryCodeResult.Bind(c => MakeStateOrProvince(stateOrProvince, c).MapOnFailure(AddressValidationError.ForInvalidStateOrProvince)));

	var postalCodeResult = Result.Create(!string.IsNullOrWhiteSpace(postalCode), () => Unit.Value, () => AddressValidationError.ForInvalidPostalCode(PostalCodeValidationError.IsEmpty))
		.Bind(_ => countryCodeResult.Bind(c => MakePostalCode(postalCode, c).MapOnFailure(AddressValidationError.ForInvalidPostalCode)));

	return ResultHelper.Merge(streetResult, cityResult, stateOrProvinceResult, countryCodeResult, postalCodeResult)
		.MapOnFailure(errors => errors.Distinct().ToArray())
		.Select(t => new Address(t.Item1, t.Item2, t.Item3, t.Item4, t.Item5));
		}
```
